export const UA = {
    AlertPost:"Рядок немає бути пуста",
    PostList_title:"Cписок постів",
    NamePost:"Назва поста",
    Description:"Описання поста",
    Increment:"Плюс",
    Decrement:"мінус",
    DeletePost:"Видалити",
    CreatePost:"Створити пост",
    NotEnoughPost:"Немає постів",
    Sorting:"Сортування",
    SortID: "По айді",
    SortTitle:"По назві",
    SortBody:"По опису" ,
    Name:"Імя",
    Sex:"Стать",
    Male: "Чоловік",
    Female: "Жінка",
    SearchPost: "Пошук поста",
  }
export const UK = {
    AlertPost: "The line must not be empty",
    PostList_title: "Post List",
    NamePost: "Post name",
    Description: "Description",
    Increment: "Increment",
    Decrement: "Decrement",
    DeletePost: "Delete",
    CreatePost: "Create new post",
    NotEnoughPost: "Not enough post",
    Sorting:"Sorting",
    SortID: "Sort by id",
    SortTitle:"Sort by name",
    SortBody:"Sort by description",
    Name:"Name",
    Sex:"Sex",
    Male: "Male",
    Female: "Female",
    SearchPost:"Search post",
}